IF (DB_ID('ToDoListDB') is null)
	CREATE DATABASE ToDoListDB	
GO 
USE ToDoListDB;

CREATE TABLE Category 
(
	[Id] INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(30) NOT NULL UNIQUE,
	[IconClassList] NVARCHAR(255) NOT NULL DEFAULT 'fa-solid fa-circle-question'
);

CREATE TABLE Task 
(
	[Id] INT PRIMARY KEY IDENTITY,
	[Content] TEXT NOT NULL,
	[Deadline] DATETIME NOT NULL,
	[CategoryId] INT NOT NULL,
	[Expired] BIT NOT NULL DEFAULT 0

	FOREIGN KEY ([CategoryId]) REFERENCES Category([Id]) ON DELETE CASCADE ON UPDATE CASCADE
);